const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Plugins.Mouse,
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.bound,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Timer,
		C3.Behaviors.Bullet,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait
	];
};
self.C3_JsPropNameTable = [
	{Tilemap: 0},
	{Mouse: 0},
	{TiledBackground: 0},
	{BoundToLayout: 0},
	{DragDrop: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{TiledBackground2: 0},
	{"8Direction": 0},
	{ScrollTo: 0},
	{Sprite4: 0},
	{Solid: 0},
	{casarosav1: 0},
	{mapagrilla: 0},
	{casaverdev2: 0},
	{Sprite5: 0},
	{toqtienda: 0},
	{Sprite6: 0},
	{tienda: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{toqinterfaz: 0},
	{colores: 0},
	{interfaztienda: 0},
	{spawncasa: 0},
	{verono: 0},
	{cerrar: 0},
	{toqetienda: 0},
	{CASAROSA: 0},
	{sepuedePoner: 0},
	{pastoverde: 0},
	{unlugar: 0},
	{Sprite7: 0},
	{toquetiendaarbol: 0},
	{ponerarbol: 0},
	{spawnverde: 0},
	{casaamarillav1: 0},
	{casaazulv1: 0},
	{Sprite11: 0},
	{casanaranjav1: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{spcasas: 0},
	{spverde: 0},
	{spawndolugare: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{TiledBackground3: 0},
	{Tilemap2: 0},
	{TiledBackground4: 0},
	{creditos: 0},
	{SpriteFont: 0},
	{banco: 0},
	{Sprite21: 0},
	{spmobi: 0},
	{seve: 0},
	{spawnmobi: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{Sprite27: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{Sprite30: 0},
	{Sprite31: 0},
	{Sprite32: 0},
	{Sprite33: 0},
	{casavioleta: 0},
	{Sprite10: 0},
	{edificiorealto: 0},
	{Sprite34: 0},
	{Sprite12: 0},
	{tacho: 0},
	{bancosinres: 0},
	{Sprite35: 0},
	{Sprite36: 0},
	{Sprite37: 0},
	{direccion: 0},
	{Sprite38: 0},
	{Timer: 0},
	{Bullet: 0},
	{npc: 0},
	{Sprite39: 0},
	{Sprite40: 0},
	{Sprite41: 0},
	{Sprite42: 0},
	{Sprite43: 0},
	{spocio: 0},
	{spawnocio: 0},
	{Sprite45: 0},
	{botonbiblio: 0},
	{Sprite47: 0},
	{Sprite15: 0},
	{botonrestaurante: 0},
	{botoncancha: 0},
	{Sprite16: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Sprite44: 0},
	{Sprite46: 0},
	{spawnarbool: 0},
	{spawnarbusto: 0},
	{spawnarbusto2: 0},
	{Sprite51: 0},
	{Sprite52: 0},
	{Sprite53: 0},
	{Sprite48: 0},
	{Sprite49: 0},
	{arbusto1: 0},
	{arbusto2: 0},
	{Sprite50: 0},
	{Sprite54: 0},
	{seveeltuto: 0},
	{momentotuto: 0},
	{Sprite55: 0},
	{Sprite56: 0},
	{Sprite57: 0},
	{Sprite58: 0},
	{Sprite59: 0},
	{Sprite60: 0},
	{Sprite61: 0},
	{spawnrandomcasa: 0},
	{SpriteFont2: 0},
	{Sprite62: 0},
	{visible: 0},
	{haagregado1: 0},
	{Sprite63: 0},
	{Sprite64: 0},
	{haagregado2: 0},
	{haagregado3: 0},
	{Sprite17: 0},
	{bancospawne: 0},
	{Sprite65: 0},
	{Sprite66: 0},
	{Sprite67: 0},
	{Sprite68: 0},
	{Sprite69: 0},
	{npc2: 0},
	{npc3: 0},
	{Sprite70: 0},
	{editmode: 0}
];

self.InstanceType = {
	Tilemap: class extends self.ITilemapInstance {},
	Mouse: class extends self.IInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	casarosav1: class extends self.ISpriteInstance {},
	mapagrilla: class extends self.ITiledBackgroundInstance {},
	casaverdev2: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	tienda: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	interfaztienda: class extends self.ISpriteInstance {},
	spawncasa: class extends self.ISpriteInstance {},
	cerrar: class extends self.ISpriteInstance {},
	CASAROSA: class extends self.ISpriteInstance {},
	sepuedePoner: class extends self.ISpriteInstance {},
	pastoverde: class extends self.ISpriteInstance {},
	unlugar: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	ponerarbol: class extends self.ISpriteInstance {},
	spawnverde: class extends self.ISpriteInstance {},
	casaamarillav1: class extends self.ISpriteInstance {},
	casaazulv1: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	casanaranjav1: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	spcasas: class extends self.ISpriteInstance {},
	spverde: class extends self.ISpriteInstance {},
	spawndolugare: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	Tilemap2: class extends self.ITilemapInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	creditos: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	banco: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	spmobi: class extends self.ISpriteInstance {},
	spawnmobi: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	casavioleta: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	edificiorealto: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	tacho: class extends self.ISpriteInstance {},
	bancosinres: class extends self.ISpriteInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	npc: class extends self.ISpriteInstance {},
	Sprite39: class extends self.ISpriteInstance {},
	Sprite40: class extends self.ISpriteInstance {},
	Sprite41: class extends self.ISpriteInstance {},
	Sprite42: class extends self.ISpriteInstance {},
	Sprite43: class extends self.ISpriteInstance {},
	spocio: class extends self.ISpriteInstance {},
	spawnocio: class extends self.ISpriteInstance {},
	Sprite45: class extends self.ISpriteInstance {},
	botonbiblio: class extends self.ISpriteInstance {},
	Sprite47: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	botonrestaurante: class extends self.ISpriteInstance {},
	botoncancha: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite44: class extends self.ISpriteInstance {},
	Sprite46: class extends self.ISpriteInstance {},
	spawnarbool: class extends self.ISpriteInstance {},
	spawnarbusto: class extends self.ISpriteInstance {},
	spawnarbusto2: class extends self.ISpriteInstance {},
	Sprite51: class extends self.ISpriteInstance {},
	Sprite52: class extends self.ISpriteInstance {},
	Sprite53: class extends self.ISpriteInstance {},
	Sprite48: class extends self.ISpriteInstance {},
	Sprite49: class extends self.ISpriteInstance {},
	arbusto1: class extends self.ISpriteInstance {},
	arbusto2: class extends self.ISpriteInstance {},
	Sprite50: class extends self.ISpriteInstance {},
	Sprite54: class extends self.ISpriteInstance {},
	Sprite55: class extends self.ISpriteInstance {},
	Sprite56: class extends self.ISpriteInstance {},
	Sprite57: class extends self.ISpriteInstance {},
	Sprite58: class extends self.ISpriteInstance {},
	Sprite59: class extends self.ISpriteInstance {},
	Sprite60: class extends self.ISpriteInstance {},
	Sprite61: class extends self.ISpriteInstance {},
	spawnrandomcasa: class extends self.ISpriteInstance {},
	SpriteFont2: class extends self.ISpriteFontInstance {},
	Sprite62: class extends self.ISpriteInstance {},
	haagregado1: class extends self.ISpriteFontInstance {},
	Sprite63: class extends self.ISpriteInstance {},
	Sprite64: class extends self.ISpriteInstance {},
	haagregado2: class extends self.ISpriteFontInstance {},
	haagregado3: class extends self.ISpriteFontInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	bancospawne: class extends self.ISpriteInstance {},
	Sprite65: class extends self.ISpriteInstance {},
	Sprite66: class extends self.ISpriteInstance {},
	Sprite67: class extends self.ISpriteInstance {},
	Sprite68: class extends self.ISpriteInstance {},
	Sprite69: class extends self.ISpriteInstance {},
	npc2: class extends self.ISpriteInstance {},
	npc3: class extends self.ISpriteInstance {},
	Sprite70: class extends self.ISpriteInstance {}
}