const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Flash,
		C3.Behaviors.Pin,
		C3.Behaviors.scrollto,
		C3.Behaviors.Physics,
		C3.Behaviors.EightDir,
		C3.Behaviors.Timer,
		C3.Behaviors.LOS,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Pathfinding,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.Camera3D,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Behaviors.Bullet.Cnds.IsEnabled,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Platform.Acts.SetDoubleJumpEnabled,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.System.Acts.SetLayoutEffectEnabled,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Platform.Acts.SetMaxFallSpeed,
		C3.Behaviors.Platform.Acts.SetDeceleration,
		C3.Behaviors.Platform.Acts.SetAcceleration,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.Keyboard.Cnds.OnKeyCode,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Cnds.CompareTime,
		C3.Plugins.Sprite.Cnds.CompareFrameTag,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetLayoutEffectParam,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Timer.Acts.PauseResumeTimer,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.Tween.Acts.ResumeAllTweens,
		C3.Behaviors.Tween.Acts.PauseAllTweens,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.System.Exps.dt,
		C3.Behaviors.EightDir.Acts.SetIgnoreInput,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Keyboard.Cnds.OnKeyCodeReleased,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Keyboard.Cnds.IsKeyCodeDown,
		C3.Plugins.Text.Acts.SetText
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Tilemap: 0},
	{Sólido: 0},
	{MapaDeTeselas: 0},
	{Tilemap2: 0},
	{Tilemap3: 0},
	{Tilemap4: 0},
	{Tilemap5: 0},
	{Tilemap6: 0},
	{espada: 0},
	{arco: 0},
	{tiempoDisparo: 0},
	{vidas: 0},
	{doble_salto: 0},
	{habilitar_espada: 0},
	{habilitar_doblesalto: 0},
	{habilitar_arco: 0},
	{paradaenX: 0},
	{ParadaenY: 0},
	{animacion: 0},
	{serpientefuego: 0},
	{state: 0},
	{habilitar_serpiente: 0},
	{piedra: 0},
	{pegaso: 0},
	{saltodosveces: 0},
	{Plataforma: 0},
	{Flash: 0},
	{Pin: 0},
	{ScrollTo: 0},
	{Physics: 0},
	{"8Direction": 0},
	{Timer: 0},
	{mujer: 0},
	{saltodoble: 0},
	{dir: 0},
	{siguiendoPj: 0},
	{vidainmortal: 0},
	{Platform: 0},
	{LineOfSight: 0},
	{inmortal: 0},
	{Bala: 0},
	{DestruirFueraDeLaEscena: 0},
	{flecha: 0},
	{Teclado: 0},
	{vidasmontruo: 0},
	{puedechocar: 0},
	{dondeesta: 0},
	{estado: 0},
	{Sine: 0},
	{Sine2: 0},
	{Tween: 0},
	{ehhh: 0},
	{nextLevel: 0},
	{acción: 0},
	{direccionadores: 0},
	{impacto: 0},
	{caída: 0},
	{trampa: 0},
	{vida: 0},
	{vida_2: 0},
	{TiledBackground: 0},
	{Text: 0},
	{TiledBackground2: 0},
	{nina: 0},
	{logo: 0},
	{textoLogo: 0},
	{Text2: 0},
	{Text3: 0},
	{contador: 0},
	{contador_flechas: 0},
	{flechaUi: 0},
	{TiledBackground3: 0},
	{uiespada: 0},
	{uisalto: 0},
	{arcoui: 0},
	{s: 0},
	{D: 0},
	{F: 0},
	{stackflechas: 0},
	{redirec: 0},
	{Bullet: 0},
	{Pathfinding: 0},
	{DestroyOutsideLayout: 0},
	{baladelmalo: 0},
	{reliquiapersa: 0},
	{Text4: 0},
	{lanza: 0},
	{TiledBackground4: 0},
	{Sprite: 0},
	{impacto2: 0},
	{tracker: 0},
	{trackerMujer: 0},
	{Browser: 0},
	{TiledBackground5: 0},
	{TiledBackground6: 0},
	{pared: 0},
	{puntos: 0},
	{score: 0},
	{highscore: 0},
	{altopunto: 0},
	{reliqpunto: 0},
	{rompiendose: 0},
	{noRompiendose: 0},
	{quesecaiga: 0},
	{quesecaigaa: 0},
	{reliquia2: 0},
	{Sprite3: 0},
	{reliquia3: 0},
	{Sprite4: 0},
	{Text5: 0},
	{Text7: 0},
	{Tilemap7: 0},
	{Tilemap8: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Tilemap9: 0},
	{Text8: 0},
	{Tilemap10: 0},
	{Text9: 0},
	{Tilemap11: 0},
	{Text10: 0},
	{Tilemap12: 0},
	{Text11: 0},
	{Text12: 0},
	{Text13: 0},
	{vidasazt: 0},
	{azteca: 0},
	{agua: 0},
	{vidasserp: 0},
	{armaserpiente: 0},
	{tiempo: 0},
	{fuegoarma: 0},
	{mevio: 0},
	{vidashacha: 0},
	{puedetp: 0},
	{hacha: 0},
	{TiledBackground7: 0},
	{TiledBackground8: 0},
	{atrapada: 0},
	{golpes: 0},
	{innitX: 0},
	{innitY: 0},
	{movimiento: 0},
	{ataque: 0},
	{perro: 0},
	{alucinacion1: 0},
	{Sprite9: 0},
	{meteorito: 0},
	{Sprite11: 0},
	{lanzazteca: 0},
	{daledale: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{cuanto: 0},
	{fuego: 0},
	{pruebaStroke: 0},
	{trampatecho: 0},
	{lanzaFlechas: 0},
	{nomevio: 0},
	{tsunamidearena: 0},
	{Sprite16: 0},
	{TiledBackground9: 0},
	{malo: 0},
	{trampapiso: 0},
	{mevieneamatar: 0},
	{medusa: 0},
	{pinchestecho: 0},
	{listo: 0},
	{ataud: 0},
	{vidamomia: 0},
	{quemada: 0},
	{momia: 0},
	{enojado: 0},
	{gatito: 0},
	{enojo: 0},
	{civil: 0},
	{mierda1: 0},
	{mierda2: 0},
	{intargeteable: 0},
	{spawneador: 0},
	{anubis: 0},
	{alma: 0},
	{vidabossazt: 0},
	{tlalocl: 0},
	{rayo: 0},
	{nopuedespawn: 0},
	{spawnrayo: 0},
	{explosion: 0},
	{puedespawn: 0},
	{rayosdir: 0},
	{rayodir: 0},
	{balanza: 0},
	{vidasammyt: 0},
	{memato: 0},
	{ammyt: 0},
	{vidasquimera: 0},
	{quimera: 0},
	{impactoleon: 0},
	{Sprite2: 0},
	{siguiendopj: 0},
	{centauro: 0},
	{Sprite8: 0},
	{Sprite15: 0},
	{poseidon: 0},
	{Sprite18: 0},
	{Text14: 0},
	{trackerr: 0},
	{Sprite19: 0},
	{fuerzaarriba: 0},
	{TiledBackground10: 0},
	{doblesaltoSi: 0},
	{doblejump: 0},
	{tridente: 0},
	{tsunami: 0},
	{pared2: 0},
	{ninfa: 0},
	{mujeranim: 0},
	{lanzaegipcia: 0},
	{melanza: 0},
	{egipcio: 0},
	{impactoespada: 0},
	{Sprite17: 0},
	{Audio: 0},
	{reliquiaazteca1: 0},
	{Sprite21: 0},
	{TiledBackground11: 0},
	{Sprite22: 0},
	{reliquiaazteca2: 0},
	{reliquiaazteca3: 0},
	{Sprite20: 0},
	{Sprite23: 0},
	{Untitled: 0},
	{reliquiaAzteca: 0},
	{reliquiaAz4: 0},
	{reliquiaegipc1: 0},
	{reliquiaegipcia2: 0},
	{reliquiaegipcia3: 0},
	{reliquiaegipcia4: 0},
	{reliquiaGriega1: 0},
	{reliquiaGriega2: 0},
	{reliquiaGriega3: 0},
	{SpriteFont: 0},
	{reliquiaGriega4: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{destello: 0},
	{TiledBackground12: 0},
	{Sprite27: 0},
	{Sprite28: 0},
	{"3DCamera": 0},
	{Sprite29: 0},
	{Sprite30: 0},
	{Sprite31: 0},
	{Sprite32: 0},
	{Sprite33: 0},
	{Sprite34: 0},
	{Sprite35: 0},
	{Sprite36: 0},
	{Sprite37: 0},
	{Sprite38: 0},
	{Sprite39: 0},
	{Sprite40: 0},
	{puedespawnear: 0},
	{spawnerbolasdefuego: 0},
	{flechacentauro: 0},
	{Sprite41: 0},
	{Sprite42: 0},
	{Sprite10: 0},
	{Sprite43: 0},
	{Sprite44: 0},
	{Sprite45: 0},
	{Sprite46: 0},
	{Sprite47: 0},
	{piramideAzteca: 0},
	{piramideAzteca2: 0},
	{Sprite48: 0},
	{Sprite49: 0},
	{Sprite24: 0},
	{Sprite50: 0},
	{Sprite51: 0},
	{Sprite52: 0},
	{Sprite53: 0},
	{Sprite54: 0},
	{Sprite55: 0},
	{Sprite56: 0},
	{Sprite57: 0},
	{Sprite58: 0},
	{Sprite59: 0},
	{Sprite60: 0},
	{Untitled2: 0},
	{Untitled3: 0},
	{Untitled4: 0},
	{Untitled5: 0},
	{Untitled6: 0},
	{Sprite61: 0},
	{Sprite62: 0},
	{Sprite63: 0},
	{Sprite64: 0},
	{Sprite65: 0},
	{Sprite66: 0},
	{Sprite67: 0},
	{Sprite68: 0},
	{CapturaDePantalla20241201ALas: 0},
	{aguagriega: 0},
	{fondo: 0},
	{Sprite69: 0},
	{Sprite70: 0},
	{Sprite71: 0},
	{Sprite72: 0},
	{Sprite73: 0},
	{Sprite74: 0},
	{tresdosuno: 0},
	{looseBossPersa: 0},
	{lba: 0},
	{Text6: 0},
	{Text15: 0},
	{Text16: 0},
	{spawner: 0},
	{spawnervidas: 0},
	{CapturaDePantalla20241202ALas: 0},
	{CapturaDePantalla20241202ALas2: 0},
	{Sprite75: 0},
	{Untitled7: 0},
	{Untitled8: 0},
	{Untitled9: 0},
	{serpienteui: 0},
	{z: 0},
	{timeloot: 0},
	{Text17: 0},
	{Sprite76: 0},
	{Sprite77: 0},
	{Sprite78: 0},
	{reliq: 0},
	{Sprite79: 0},
	{highestscore: 0},
	{Sprite80: 0},
	{IMG_: 0},
	{Sprite81: 0},
	{flechas: 0},
	{Vidas: 0},
	{intensidadfx: 0},
	{agarrolaserp: 0},
	{fxenable: 0},
	{Tecla_Salto: 0},
	{Tecla_Espada: 0},
	{Tecla_Arco: 0},
	{Tecla_Fuego: 0},
	{arcade: 0}
];

self.InstanceType = {
	Tilemap: class extends self.ITilemapInstance {},
	MapaDeTeselas: class extends self.ITilemapInstance {},
	Tilemap2: class extends self.ITilemapInstance {},
	Tilemap3: class extends self.ITilemapInstance {},
	Tilemap4: class extends self.ITilemapInstance {},
	Tilemap5: class extends self.ITilemapInstance {},
	Tilemap6: class extends self.ITilemapInstance {},
	mujer: class extends self.ISpriteInstance {},
	saltodoble: class extends self.ISpriteInstance {},
	inmortal: class extends self.ISpriteInstance {},
	espada: class extends self.ISpriteInstance {},
	arco: class extends self.ISpriteInstance {},
	flecha: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	ehhh: class extends self.ISpriteInstance {},
	nextLevel: class extends self.ISpriteInstance {},
	direccionadores: class extends self.ISpriteInstance {},
	impacto: class extends self.ISpriteInstance {},
	trampa: class extends self.ISpriteInstance {},
	vida: class extends self.ISpriteInstance {},
	vida_2: class extends self.ITiledBackgroundInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Text: class extends self.ITextInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	nina: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	textoLogo: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	contador_flechas: class extends self.ISpriteFontInstance {},
	flechaUi: class extends self.ISpriteInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	uiespada: class extends self.ISpriteInstance {},
	uisalto: class extends self.ISpriteInstance {},
	arcoui: class extends self.ISpriteInstance {},
	s: class extends self.ITextInstance {},
	D: class extends self.ITextInstance {},
	F: class extends self.ITextInstance {},
	stackflechas: class extends self.ISpriteInstance {},
	baladelmalo: class extends self.ISpriteInstance {},
	reliquiapersa: class extends self.ISpriteInstance {},
	Text4: class extends self.ITextInstance {},
	lanza: class extends self.ISpriteInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	impacto2: class extends self.ISpriteInstance {},
	tracker: class extends self.ISpriteInstance {},
	trackerMujer: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	pared: class extends self.ISpriteInstance {},
	puntos: class extends self.ISpriteFontInstance {},
	score: class extends self.ISpriteFontInstance {},
	highscore: class extends self.ISpriteFontInstance {},
	altopunto: class extends self.ISpriteFontInstance {},
	reliqpunto: class extends self.ISpriteInstance {},
	quesecaiga: class extends self.ISpriteInstance {},
	quesecaigaa: class extends self.ISpriteInstance {},
	reliquia2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	reliquia3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Text5: class extends self.ITextInstance {},
	Text7: class extends self.ITextInstance {},
	Tilemap7: class extends self.ITilemapInstance {},
	Tilemap8: class extends self.ITilemapInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Tilemap9: class extends self.ITilemapInstance {},
	Text8: class extends self.ITextInstance {},
	Tilemap10: class extends self.ITilemapInstance {},
	Text9: class extends self.ITextInstance {},
	Tilemap11: class extends self.ITilemapInstance {},
	Text10: class extends self.ITextInstance {},
	Tilemap12: class extends self.ITilemapInstance {},
	Text11: class extends self.ITextInstance {},
	Text12: class extends self.ITextInstance {},
	Text13: class extends self.ITextInstance {},
	azteca: class extends self.ISpriteInstance {},
	agua: class extends self.ISpriteInstance {},
	serpientefuego: class extends self.ISpriteInstance {},
	armaserpiente: class extends self.ISpriteInstance {},
	fuegoarma: class extends self.ISpriteInstance {},
	hacha: class extends self.ISpriteInstance {},
	TiledBackground7: class extends self.ITiledBackgroundInstance {},
	TiledBackground8: class extends self.ITiledBackgroundInstance {},
	perro: class extends self.ISpriteInstance {},
	alucinacion1: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	meteorito: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	lanzazteca: class extends self.ISpriteInstance {},
	daledale: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	fuego: class extends self.ISpriteInstance {},
	pruebaStroke: class extends self.ISpriteInstance {},
	trampatecho: class extends self.ISpriteInstance {},
	lanzaFlechas: class extends self.ISpriteInstance {},
	tsunamidearena: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	TiledBackground9: class extends self.ITiledBackgroundInstance {},
	trampapiso: class extends self.ISpriteInstance {},
	medusa: class extends self.ISpriteInstance {},
	pinchestecho: class extends self.ISpriteInstance {},
	ataud: class extends self.ISpriteInstance {},
	momia: class extends self.ISpriteInstance {},
	gatito: class extends self.ISpriteInstance {},
	civil: class extends self.ISpriteInstance {},
	mierda1: class extends self.ISpriteInstance {},
	mierda2: class extends self.ISpriteInstance {},
	anubis: class extends self.ISpriteInstance {},
	alma: class extends self.ISpriteInstance {},
	tlalocl: class extends self.ISpriteInstance {},
	rayo: class extends self.ISpriteInstance {},
	spawnrayo: class extends self.ISpriteInstance {},
	explosion: class extends self.ISpriteInstance {},
	rayosdir: class extends self.ISpriteInstance {},
	rayodir: class extends self.ISpriteInstance {},
	balanza: class extends self.ISpriteInstance {},
	ammyt: class extends self.ISpriteInstance {},
	pegaso: class extends self.ISpriteInstance {},
	quimera: class extends self.ISpriteInstance {},
	impactoleon: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	centauro: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	poseidon: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Text14: class extends self.ITextInstance {},
	trackerr: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	fuerzaarriba: class extends self.ISpriteInstance {},
	TiledBackground10: class extends self.ITiledBackgroundInstance {},
	doblejump: class extends self.ISpriteInstance {},
	tridente: class extends self.ISpriteInstance {},
	tsunami: class extends self.ISpriteInstance {},
	pared2: class extends self.ISpriteInstance {},
	ninfa: class extends self.ISpriteInstance {},
	mujeranim: class extends self.ISpriteInstance {},
	lanzaegipcia: class extends self.ISpriteInstance {},
	egipcio: class extends self.ISpriteInstance {},
	impactoespada: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	reliquiaazteca1: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	TiledBackground11: class extends self.ITiledBackgroundInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	reliquiaazteca2: class extends self.ISpriteInstance {},
	reliquiaazteca3: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Untitled: class extends self.ISpriteInstance {},
	reliquiaAzteca: class extends self.ISpriteInstance {},
	reliquiaAz4: class extends self.ISpriteInstance {},
	reliquiaegipc1: class extends self.ISpriteInstance {},
	reliquiaegipcia2: class extends self.ISpriteInstance {},
	reliquiaegipcia3: class extends self.ISpriteInstance {},
	reliquiaegipcia4: class extends self.ISpriteInstance {},
	reliquiaGriega1: class extends self.ISpriteInstance {},
	reliquiaGriega2: class extends self.ISpriteInstance {},
	reliquiaGriega3: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	reliquiaGriega4: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	destello: class extends self.ISpriteInstance {},
	TiledBackground12: class extends self.ITiledBackgroundInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	_3DCamera: class extends self.IInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	Sprite39: class extends self.ISpriteInstance {},
	Sprite40: class extends self.ISpriteInstance {},
	spawnerbolasdefuego: class extends self.ISpriteInstance {},
	flechacentauro: class extends self.ISpriteInstance {},
	Sprite41: class extends self.ISpriteInstance {},
	Sprite42: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite43: class extends self.ISpriteInstance {},
	Sprite44: class extends self.ISpriteInstance {},
	Sprite45: class extends self.ISpriteInstance {},
	Sprite46: class extends self.ISpriteInstance {},
	Sprite47: class extends self.ISpriteInstance {},
	piramideAzteca: class extends self.ISpriteInstance {},
	piramideAzteca2: class extends self.ISpriteInstance {},
	Sprite48: class extends self.ISpriteInstance {},
	Sprite49: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite50: class extends self.ISpriteInstance {},
	Sprite51: class extends self.ISpriteInstance {},
	Sprite52: class extends self.ISpriteInstance {},
	Sprite53: class extends self.ISpriteInstance {},
	Sprite54: class extends self.ISpriteInstance {},
	Sprite55: class extends self.ISpriteInstance {},
	Sprite56: class extends self.ISpriteInstance {},
	Sprite57: class extends self.ISpriteInstance {},
	Sprite58: class extends self.ISpriteInstance {},
	Sprite59: class extends self.ISpriteInstance {},
	Sprite60: class extends self.ISpriteInstance {},
	Untitled2: class extends self.ISpriteInstance {},
	Untitled3: class extends self.ISpriteInstance {},
	Untitled4: class extends self.ISpriteInstance {},
	Untitled5: class extends self.ISpriteInstance {},
	Untitled6: class extends self.ISpriteInstance {},
	Sprite61: class extends self.ISpriteInstance {},
	Sprite62: class extends self.ISpriteInstance {},
	Sprite63: class extends self.ISpriteInstance {},
	Sprite64: class extends self.ISpriteInstance {},
	Sprite65: class extends self.ISpriteInstance {},
	Sprite66: class extends self.ISpriteInstance {},
	Sprite67: class extends self.ISpriteInstance {},
	Sprite68: class extends self.ISpriteInstance {},
	CapturaDePantalla20241201ALas: class extends self.ISpriteInstance {},
	aguagriega: class extends self.ISpriteInstance {},
	fondo: class extends self.ISpriteInstance {},
	Sprite69: class extends self.ISpriteInstance {},
	Sprite70: class extends self.ISpriteInstance {},
	Sprite71: class extends self.ISpriteInstance {},
	Sprite72: class extends self.ISpriteInstance {},
	Sprite73: class extends self.ISpriteInstance {},
	Sprite74: class extends self.ISpriteInstance {},
	tresdosuno: class extends self.ISpriteInstance {},
	looseBossPersa: class extends self.ITextInstance {},
	lba: class extends self.ITextInstance {},
	Text6: class extends self.ITextInstance {},
	Text15: class extends self.ITextInstance {},
	Text16: class extends self.ITextInstance {},
	spawner: class extends self.ISpriteInstance {},
	spawnervidas: class extends self.ISpriteInstance {},
	CapturaDePantalla20241202ALas: class extends self.ISpriteInstance {},
	CapturaDePantalla20241202ALas2: class extends self.ISpriteInstance {},
	Sprite75: class extends self.ISpriteInstance {},
	Untitled7: class extends self.ISpriteInstance {},
	Untitled8: class extends self.ISpriteInstance {},
	Untitled9: class extends self.ISpriteInstance {},
	serpienteui: class extends self.ISpriteInstance {},
	z: class extends self.ITextInstance {},
	timeloot: class extends self.ISpriteInstance {},
	Text17: class extends self.ITextInstance {},
	Sprite76: class extends self.ISpriteInstance {},
	Sprite77: class extends self.ISpriteInstance {},
	Sprite78: class extends self.ISpriteInstance {},
	reliq: class extends self.ISpriteInstance {},
	Sprite79: class extends self.ISpriteInstance {},
	highestscore: class extends self.ITextInstance {},
	Sprite80: class extends self.ISpriteInstance {},
	IMG_: class extends self.ISpriteInstance {},
	Sprite81: class extends self.ISpriteInstance {}
}